### ISSUE TITLE
Example configuration for ROCm image

### ISSUE THREAD

**Issue by johncadengo** [ai-dock/comfyui#136]
Hi. Thanks for all of your hard work. Love the AI-Dock collection.

I just cloned the repository and am working off of the default Docker compose file:

```
services:
  supervisor:
    platform: linux/amd64
    build:
      context: ./build
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.10}
        PYTORCH_VERSION: ${PYTORCH_VERSION:-2.4.1}
        COMFYUI_BUILD_REF: ${COMFYUI_BUILD_REF:-}
        # Base on Python image which is base + python + jupyter
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/ai-dock/python:${PYTHON_VERSION:-3.10}-v2-cuda-12.1.1-base-22.04}
      tags:
        - "ghcr.io/ai-dock/comfyui:${IMAGE_TAG:-pytorch-${PYTORCH_VERSION:-2.3.0}-py3.10-v2-cuda-12.1.1-base-22.04}"
        
    image: ghcr.io/ai-dock/comfyui:${IMAGE_TAG:-pytorch-${PYTORCH_VERSION:-2.3.0}-py3.10-v2-cuda-12.1.1-base-22.04}
```

Is there a way to use .env variables to support the ROCm image or should I just edit the image to point to the one I want?

I'm wondering because there are a few args that depend on the python and pytorch versions. The pytorch version in the default Docker compose file refers to the CUDA version of pytorch.
